apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-date
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: date-job
              image: #nome imagem